---
- hosts: $hosts
  sudo: yes
  # accelerate: true 
  vars_files:
    - vars/asterisk_vars.yml

  tasks:
    - include: asterisk.yml

  handlers:
    - name: restart dahdi
      command: /etc/init.d/dahdi restart
