---
- hosts: $hosts
  sudo: yes
  # accelerate: true 
  vars_files:
    - vars/asterisk_config_vars.yml
    - vars/asterisk_vars.yml

  tasks:
    - include: asterisk.yml
    - include: asterisk_databases.yml

  handlers:
    - name: restart dahdi
      command: /etc/init.d/dahdi restart
