---
- include: user.yml

- name: Disable root login over ssh
  command: sed -i.bak 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
  notify:
    - restart ssh

- name: Allow SSH Agent Forwarding
  lineinfile: dest=/etc/ssh/sshd_config backup=yes 
    line='AllowAgentForwarding yes'
    regexp='AllowAgentForwarding yes' 
  notify:
    - restart ssh


 # disable telnet
 # #     default
 # # ftp, rlogin, rsh
 # # Password Restrictions
 # #   password aging?
 # #   password reuse
 # # Lock accounts after Login Failures
 # # no accounts with empty passwords
 # # no uid0 accounts
 # # Networking
 # #   IPtables
 # #   Check listening services
 # #
 # # Intrusion Detection System
 # # Backups
 # #   Server
 # #   Database
 # #   Logs
 # #
 # # http://www.linux-sxs.org/security/scheck.html
